//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administradore
    {
        public int id_administrador { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string cargo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
