//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administradore : Usuario
    {
        public int id_administrador { get; set; }

        public string cargo { get; set; }

        public Administradore(int id_administrador, int id_usuario, string documento, string nombre, string apellido, int edad,
            string correo_electronico, string contraseña, string tipo_usuario, string cargo) :
            base(id_usuario, documento, nombre, apellido, edad, correo_electronico, contraseña, tipo_usuario)
        {
            this.id_administrador = id_administrador;
            this.cargo = cargo;
        }

        public virtual Usuario Usuario { get; set; }
    }
}
