//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculos.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class CitaTaller
    {
        public int Codigo { get; set; }
        public string DocCliente { get; set; }
        public string PlacaVeh { get; set; }
        public int CodTipoServicio { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }

        [JsonIgnore]
        public virtual TipoServicio TipoServicio { get; set; }
        [JsonIgnore]
        public virtual Cliente Cliente { get; set; }
        [JsonIgnore]
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
