//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculos.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Citas_Taller
    {
        public int id_cita { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string placa_vehiculo { get; set; }
        public Nullable<int> id_servicio { get; set; }
        public Nullable<System.DateTime> fecha_cita { get; set; }
        public Nullable<System.TimeSpan> hora_cita { get; set; }

        [JsonIgnore]
        public virtual Servicios_de_Taller Servicios_de_Taller { get; set; }

        [JsonIgnore]
        public virtual Usuario Usuario { get; set; }

        [JsonIgnore]
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
