//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int id_cliente { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public Nullable<int> id_tipo_cliente { get; set; }
    
        public virtual Tipo_Cliente Tipo_Cliente { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
