//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VentaVehiculosEntities2 : DbContext
    {
        public VentaVehiculosEntities2()
            : base("name=VentaVehiculosEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administradore> Administradores { get; set; }
        public virtual DbSet<Citas_Taller> Citas_Taller { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Estado_Servicio> Estado_Servicio { get; set; }
        public virtual DbSet<Estado_Vehiculo> Estado_Vehiculo { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<Garantia> Garantias { get; set; }
        public virtual DbSet<Permiso> Permisos { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Servicios_de_Taller> Servicios_de_Taller { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_Cliente> Tipo_Cliente { get; set; }
        public virtual DbSet<Tipo_Garantia> Tipo_Garantia { get; set; }
        public virtual DbSet<Tipo_Servicio> Tipo_Servicio { get; set; }
        public virtual DbSet<Tipo_Vehiculo> Tipo_Vehiculo { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Vehiculo> Vehiculos { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
    }
}
