//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculos.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Garantia
    {
        public int id_garantia { get; set; }
        public Nullable<int> id_venta { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_tipo_garantia { get; set; }

        [JsonIgnore]
        public virtual Tipo_Garantia Tipo_Garantia { get; set; }

        [JsonIgnore]
        public virtual Venta Venta { get; set; }
    }
}
