//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculos.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public int id_permiso { get; set; }
        public string descripcion_permiso { get; set; }
        public Nullable<int> id_rol { get; set; }

        [JsonIgnore]
        public virtual Role Role { get; set; }
    }
}
