//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculos.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int Codigo { get; set; }
        public int IdCliente { get; set; }
        public int IdVendedor { get; set; }
        public int IdVeh { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaVen { get; set; }

        [JsonIgnore]
        public virtual Cliente Cliente { get; set; }
        [JsonIgnore]
        public virtual Vehiculo Vehiculo { get; set; }
        [JsonIgnore]
        public virtual Vendedor Vendedor { get; set; }
    }
}
