//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Administradores = new HashSet<Administradore>();
            this.Citas_Taller = new HashSet<Citas_Taller>();
            this.Clientes = new HashSet<Cliente>();
            this.Roles = new HashSet<Role>();
            this.Ventas = new HashSet<Venta>();
        }
    
        public int id_usuario { get; set; }
        public string documento { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int edad { get; set; }
        public string correo_electronico { get; set; }
        public string contraseña { get; set; }
        public string tipo_usuario { get; set; }

        public Usuario (int id_usuario, string documento, string nombre, string apellido, int edad, string correo_electronico, string contraseña, string tipo_usuario)
        {
            this.id_usuario = id_usuario;
            this.documento = documento;
            this.nombre = nombre;
            this.apellido = apellido;
            this.edad = edad;
            this.correo_electronico = correo_electronico;
            this.contraseña = contraseña;
            this.tipo_usuario = tipo_usuario;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Administradore> Administradores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas_Taller> Citas_Taller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
