//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculos.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Citas_Taller = new HashSet<Citas_Taller>();
            this.Servicios_de_Taller = new HashSet<Servicios_de_Taller>();
            this.Ventas = new HashSet<Venta>();
        }
    
        public string placa_vehiculo { get; set; }
        public string marca { get; set; }
        public Nullable<int> modelo { get; set; }
        public Nullable<long> precio { get; set; }
        public Nullable<int> kilometraje { get; set; }
        public Nullable<int> id_estado_vehiculo { get; set; }
        public Nullable<int> id_tipo_vehiculo { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas_Taller> Citas_Taller { get; set; }

        [JsonIgnore]
        public virtual Estado_Vehiculo Estado_Vehiculo { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicios_de_Taller> Servicios_de_Taller { get; set; }

        [JsonIgnore]
        public virtual Tipo_Vehiculo Tipo_Vehiculo { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
